---
  - name: install "nginx" package
    yum:
      name: nginx
      state: latest
    notify: nginx start

  - name: install "php" package
    yum:
      name: php
      state: latest
      
  - name: install "MariaDB" package
    yum:
      name: mariadb-server
      state: latest
    notify: mariadb start

  - name: install "php-fpm" package
    yum:
      name: php-fpm
      state: latest
    notify: php-fpm start

  - name: copy the nginx config file and restart nginx
    template:
      src: /etc/ansible/roles/ansible-nginx-php-fpm-centos6/files/default.j2
      dest: /etc/nginx/conf.d/default.conf
    become: yes

  - name: copy the nginx config file and restart nginx
    copy:
      src: /etc/ansible/roles/ansible-nginx-php-fpm-centos6/files/nginx.conf
      dest: /etc/nginx/nginx.conf
    become: yes

  - name: copying t.php file for phpinfo
    copy:
      src: /etc/ansible/roles/ansible-nginx-php-fpm-centos6/files/t.php
      dest: /var/www/html/
    become: yes
